### ISSUE TITLE
Doesn't work at all in Chrome

### ISSUE THREAD

**Issue by buisine** [codekraft-studio/vue-record#1]
Hey,
this works great in firefox, but using :
Chrome Latest Version 77.0.3865.90 (Build officiel) (64 bits) it doesn't

What i get on the console : 
VueRecord.umd.js?6cb0:4158 DOMException

  | _callee$ | @ | VueRecord.umd.js?6cb0:4158
  | tryCatch | @ | VueRecord.umd.js?6cb0:2463
  | invoke | @ | VueRecord.umd.js?6cb0:2689
  | prototype.<computed> | @ | VueRecord.umd.js?6cb0:2515
  | asyncGeneratorStep | @ | VueRecord.umd.js?6cb0:4080
  | _throw | @ | VueRecord.umd.js?6cb0:4106
  | Promise.then (async) |   |  
  | asyncGeneratorStep | @ | VueRecord.umd.js?6cb0:4090
  | _next | @ | VueRecord.umd.js?6cb0:4102
  | eval | @ | VueRecord.umd.js?6cb0:4109
  | F | @ | VueRecord.umd.js?6cb0:2014
  | eval | @ | VueRecord.umd.js?6cb0:4098
  | start | @ | VueRecord.umd.js?6cb0:4169
  | startRecording | @ | VueRecord.umd.js?6cb0:4317
  | invoker | @ | vue.common.js?2371:2029
  | fn._withTask.fn._withTask | @ | vue.common.js?2371:1828

Demo page fails as well on chrome

**Comment by b4dnewz** [comment]
have you checked that your browser recognizes the media device such as webcam or microphone?
usually DOM Exceptions (for this plugin) means you don't have any microphone/webcam attached when trying to record or that you denied the permission for the browser to access the device

**Comment by buisine** [comment]
You are right, was initially testing about firefox fine , this doesnt come
to my mind.
Thanks

Cordialement.
D. Buisine


Le dim. 13 oct. 2019 à 05:32, Filippo Conti <notifications@github.com> a
écrit :
