### ISSUE TITLE
Possible to publish the uncompressed demo code?

### ISSUE THREAD

**Issue by mysteriousHerb** [codekraft-studio/vue-record#13]
Hi There are many good things I would like to implement from what you have in the demo code. But the demo code is in the compressed state that I can no longer understand. Is it possible to publish the original .vue file?

**Comment by impronta48** [comment]
Yes! The demo source code would be great!

**Comment by b4dnewz** [comment]
@impronta48 it's [already available](https://github.com/codekraft-studio/vue-record/tree/master/src) relevant code is `App.vue` and `main.js`
