### ISSUE TITLE
Unable to use record - TypeError: Cannot read property 'getUserMedia' of undefined

### ISSUE THREAD

**Issue by alpeshgit** [codekraft-studio/vue-record#3]
Unable to implement the componet in my Vue application. The demo page works in my browser though.
In my Vue Component
`<vue-record-audio  mode="press" @stream="onStream" @result="onResult" />`

And in main.js
`import VueRecord from '@codekraft-studio/vue-record'
Vue.use(VueRecord)`

Browser Info :
Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by b4dnewz** [comment]
it's really strange because the components check for media support on mount, [see](https://github.com/codekraft-studio/vue-record/blob/master/src/components/RecorderMixin.js#L108-L112) relavant part of code.

Which browser are you using? And did you see any warn in console?

**Comment by b4dnewz** [comment]
need more informations or a repro code

**Comment by rishpandey** [comment]
I ran into a similar issue on my local dev machine in chrome where local sites served via HTTP can't even ask for microphone permission. 

You can fix it by going to  ```chrome://flags/#unsafely-treat-insecure-origin-as-secure``` and add your domain there.

This may help. 
https://support.google.com/chrome/thread/8602710?hl=en
