### ISSUE TITLE
How to use it programmatically?

### ISSUE THREAD

**Issue by supakornkim** [codekraft-studio/vue-record#4]
Hello,

Is there a way to trigger to recording audio from JS code without pressing button by user?

Thank you.

**Comment by b4dnewz** [comment]
Hi, you can use [refs](https://vuejs.org/v2/api/#ref) to access the component and then call the exposed methods such as: **start, stop, pause, resume**

**Comment by supakornkim** [comment]
Hello,

I try .. but error 
<VueRecordAudio ref="voicerecord" @result="onResult" :mode="recMode" />
this.$refs.voicerecord.start()
VM4033:37 [Vue warn]: Error in v-on handler: "TypeError: this.$refs.voicerecord.start is not a function"

but I use this and it works
<VueRecordAudio id="voicerecord" @result="onResult" :mode="recMode" />
document.getElementById('voicerecord').dispatchEvent(new Event('mouseup'))

**Comment by b4dnewz** [comment]
Hi, this is really strange because the methods are defined, checkout this screenshot:
```html
<vue-record-audio ref="Recorder" />
```

```js
export default {
  mounted() {
    console.log(this.$refs.Recorder.start)
  }
}
```

![image](https://user-images.githubusercontent.com/29862596/71580570-8be19580-2b01-11ea-9fba-290e03c87841.png)

Probably is something else in your code, If you copy n paste an extract of it, I try to help

**Comment by supakornkim** [comment]
Hello, ok. it is work now. 

It does not work because I have multiple of <VueRecordAudio> components.
So, when I make it to have only 1 component, start() and stop() now work!

Thank you so much

**Comment by b4dnewz** [comment]
> It does not work because I have multiple of components.
So, when I make it to have only 1 component, start() and stop() now work!

multiple vue-record components? if so, it sound like a bug to me, maybe I should check..
can you paste some of the code, i'm a little bit curious
