### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by mreduar** [codekraft-studio/vue-record#7]
I'm trying to import this package but there's no way I can. Look at the npm folder and I see only the dist folder. And there's only js compiled with webpack there. Is this okay?

This is what I've done so far.
```
import { VueRecord } from '@codekraft-studio/vue-record'
Vue.use(VueRecord)
```
in console 
`Uncaught TypeError: Cannot read property 'install' of undefined`
Try this too.
```
import { VueRecord } from '@codekraft-studio/vue-record'
    ...
    //In another component
    components: {
        VueRecord,
    },
```
in console
`Unknown custom element: <vue-record>`

**Comment by b4dnewz** [comment]
hi, checkout the [installation](https://github.com/codekraft-studio/vue-record#installation) example, the curly brackets are not required.

```js
import VueRecord from '@codekraft-studio/vue-record'
Vue.use(VueRecord)
```
